### PR TITLE
hello-rails-back-end

### PR DESCRIPTION
**Pull request by AhmadiGu**
### Backend part

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).
-https://github.com/AhmadiGu/hello_react_front_end/pull/1

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @AhmadiGu 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

- [ ] Dear @AhmadiGu, It's mandatory to have your backend link on your frontend RADME file and your frontend link on your backend README file. Please make sure to add the link before the next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AhmadiGu** [comment]
@TadesseDev Hi hope to be fine I just want to mention that the readme file contains both front-end and back-end repositories kindly check the git clone part.

**Review by AshakaE — APPROVED** [review]
Hi @AhmadiGu , 

### Highlights ✨ 

- Code base looks clean 👍 
- Pull request 👌 
- Github flow ✅ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
dear @AhmadiGu, Thanks for reaching out. I see you have mentioned the repos in the readme `set up` section. That is nice. But we are expected to check for a link to both parts. which I couldn't find.

**Pull request merged**
